---
name: Deploy Asset Metadata App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy asset metadata (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      APP_PATH: 'edge-apps/asset-metadata'
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}
      API_BASE_URL: ${{ inputs.environment == 'stage' && 'https://api.screenlyappstage.com/' || 'https://api.screenlyapp.com/' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}