name: Deploy Edge App
description: |
  Manually deploy any edge app to either the staging or production environment.
  Always uses the latest master branch.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

      edge_app_name:
        description: 'Folder name of the edge app (under edge-apps/)'
        required: true
        default: ''

jobs:
  deploy:
    name: Deploy ${{ inputs.edge_app_name }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      APP_PATH: edge-apps/${{ inputs.edge_app_name }}
      MANIFEST_FILE_NAME: ${{ inputs.environment == 'production' && 'screenly.yml' || 'screenly_qc.yml' }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set API Token
        id: set_token
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            echo "TOKEN=${{ secrets.SCREENLY_API_TOKEN }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            echo "TOKEN=${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}" >> $GITHUB_OUTPUT
          else
            echo "Invalid environment selected"; exit 1;
          fi

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ steps.set_token.outputs.TOKEN }}
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }} --manifest-file=${{ env.APP_PATH }}/${{ env.MANIFEST_FILE_NAME }}
