name: List Screens via Screenly CLI v2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to list screens (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

jobs:
  list-screens:
    name: List Screens from ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}
      API_BASE_URL: ${{ inputs.environment == 'stage' && 'https://api.screenlyappstage.com/' || 'https://api.screenlyapp.com/' }}

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Download screenly-cli binary
        run: |
          wget -q -O screenly-cli https://github.com/Screenly/cli/releases/download/v1.0.3/screenly-cli-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf screenly-cli
          chmod +x screenly

      - name: Run `screen list` and print output
        run: |
          echo "📡 Listing screens from: $API_BASE_URL"
          export API_TOKEN=$SCREENLY_API_TOKEN
          ./screenly screen list
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}
          API_TOKEN: ${{ env.SCREENLY_API_TOKEN }}

      - name: Run `screen list` and print output without export API_TOKEN
        run: |
          echo "📡 Listing screens from: $API_BASE_URL"
          export API_TOKEN=$SCREENLY_API_TOKEN
          ./screenly screen list

      - name: Run `screen edge-app list` and print output without export API_TOKEN
        run: |
          echo "📡 Listing screens from: $API_BASE_URL"
          ./screenly edge-app list
