name: List Screens via Screenly CLI v2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to list screens (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

jobs:
  list-screens:
    name: List Screens from ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}
      API_BASE_URL: ${{ inputs.environment == 'stage' && 'https://api.screenlyappstage.com/' || 'https://api.screenlyapp.com/' }}

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Set timestamp
        id: list-screens

      - name: Run `screen list` using screenly/cli@master
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: screen list
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}

      - name: Run `edge-app list` using screenly/cli@master
        id: edge-app-list
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: edge-app list
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}

      - name: Upload CLI output
        uses: actions/upload-artifact@v4
        with:
          name: run-cli-output-${{ steps.timestamp.outputs.timestamp }}
          path: /tmp/screenly_cli_command_output.txt
