name: List Screens and Edge Apps

on:
  pull_request:
    branches:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: List screens
    steps:
      - uses: actions/checkout@v3
      - id: list-screens
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: screen list

  second-job:
    runs-on: ubuntu-latest
    name: List edge apps
    steps:
      - uses: actions/checkout@v3
      - id: list-edge-apps
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: edge-app list
