name: List Screens and Edge Apps

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to list screens'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  test-github-action-workflow:
    runs-on: ubuntu-latest
    name: List screens
    steps:
      - uses: actions/checkout@v3
      - id: list-screens
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: screen list

      - id: list-edge-apps
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: edge-app list


