---
name: Update Edge App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update edge app (stage or production)'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

      edge_app_name:
        description: 'Folder name of the edge app (under edge-apps/)'
        required: true

  push:
    branches:
      - master
    paths:
      - 'edge-apps/**'

run-name: Deploying ${{ inputs.edge_app_name || 'edge app' }} to ${{ inputs.environment || 'stage' }}

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment == 'stage' && 'Staging (QC)' || 'Production' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'stage' }}
    env:
      APP_PATH: edge-apps/${{ inputs.edge_app_name }}
      MANIFEST_FILE_NAME: ${{ inputs.environment == 'stage' && 'screenly_qc.yml' || 'screenly.yml' }}
      API_BASE_URL: ${{ inputs.environment == 'stage' && 'https://api.screenlyappstage.com/' || 'https://api.screenlyapp.com/' }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Deploy Edge App to ${{ inputs.environment }}
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: edge-app deploy --path="${{ env.APP_PATH }}" --manifest-file="${{ env.APP_PATH }}/${{ env.MANIFEST_FILE_NAME }}"
